version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: accountscarddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  spring-app:
    image: densoftdev/account-card-service:latest
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/accountscarddb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"

volumes:
  pg_data: # Define a volume to persist PostgreSQL data
