apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vMzQuNjcuMjA1LjE1NTo1NDMyL2FjY291bnRzY2FyZGRi
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=
  SPRING_DATASOURCE_PASSWORD: ZGVWMDEyMzQh
