apiVersion: v1
kind: Service
metadata:
  name: account-card-service-service
spec:
  selector:
    app: account-card-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
